[package]
name = "kit"
version = "1.4.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
arboard = "3.4"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5.53", features = ["derive"] }
colored = "2.1"
dirs = "6.0.0"
dotenvy = "0.15"
env_logger = "0.11"
log = "0.4"
open = "5.3.3"
reqwest = { version = "0.12.28", features = ["json", "blocking"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
inquire = "0.7"
spinoff = "0.8"
openssl = { version = "0.10", features = ["vendored"] }
